---

- name: install some small, awesome packages to boost your life
  apt: name={{item}} state=present
  with_items:
    - cloc
    - htop
    - pinfo
    - proxychains
    - ranger
    - rlwrap
    - texinfo
    - tig
    - tmux

# zsh and oh-my-zsh
- name: install zsh
  apt: name={{item}} state=present
  with_items:
    - zsh
    - zsh-lover
