---

- name: install some small, awesome packages to boost your life
  pacman: name={{item}} state=present
  with_items:
    - cloc
    - htop
    - pinfo
    - proxychains
    - ranger
    - rlwrap
    - texinfo
    - tig
    - tmux
    - docker
    - cmus
    - nethogs

# zsh and oh-my-zsh
- name: install zsh
  pacman: name={{item}} state=present
  with_items:
    - zsh
    - zsh-lover


- include: base.yml
  sudo: no
            
- set_fact:
   role_basic_done: true

